import datetime
import time
import streamlit as st

default_inputs = {
    'tinyint': st.number_input,
    'smallint': st.number_input,
    'mediumint': st.number_input,
    'int': st.number_input,
    'bigint': st.number_input,
    'float': st.number_input,
    'double': st.number_input,
    'decimal': st.number_input,
    'date': st.date_input,
    'datetime': st.date_input,
    'timestamp': st.date_input,
    'time': st.time_input,
    'year': st.number_input,
    'char': st.text_input,
    'varchar': st.text_input,
    'tinyblob': st.file_uploader,
    'tinytext': st.text_area,
    'blob': st.file_uploader,
    'text': st.text_area,
    'mediumblob': st.file_uploader,
    'mediumtext': st.text_area,
    'longblob': st.file_uploader,
    'longtext': st.text_area,
    'enum': st.selectbox,
    'set': st.multiselect,
    'binary': st.file_uploader,
    'varbinary': st.file_uploader,
    'bit': st.number_input,
    'tinyint unsigned': st.number_input,
    'smallint unsigned': st.number_input,
    'mediumint unsigned': st.number_input,
    'int unsigned': st.number_input,
    'bigint unsigned': st.number_input,
    'float unsigned': st.number_input,
    'double unsigned': st.number_input,
    'decimal unsigned': st.number_input,
    'timestamp unsigned': st.date_input,
    'bit unsigned': st.number_input,
    'integer': st.number_input,
    'numeric': st.number_input,
    'real': st.number_input,
    'double precision': st.number_input,
    'serial': st.number_input,
    'bigserial': st.number_input,
    'timestamp with time zone': st.date_input,
    'time with time zone': st.time_input,
    'interval': st.number_input,
    'boolean': st.checkbox,
    'character varying': st.text_input,
    'bytea': st.file_uploader,
    'tsvector': st.text_area,
    'tsquery': st.text_input,
    'uuid': st.text_input,
    'xml': st.file_uploader,
    'json': st.text_area,
    'jsonb': st.text_area,
    'array': st.text_area,
    'inet': st.text_input,
    'cidr': st.text_input,
    'macaddr': st.text_input,
    'bit varying': st.number_input,
    'varbit': st.number_input,
    'geometry': st.file_uploader,
    'geography': st.file_uploader,
    'box': st.file_uploader,
    'line': st.file_uploader,
    'lseg': st.file_uploader,
    'path': st.file_uploader,
    'point': st.file_uploader,
    'polygon': st.file_uploader,
    'circle': st.file_uploader,
    'citext': st.text_input,
    'hstore': st.text_area,
    'ltree': st.text_input,
    'int4range': st.number_input,
    'int8range': st.number_input,
    'numrange': st.number_input,
    'tsrange': st.text_input,
    'tstzrange': st.text_input,
    'daterange': st.date_input,
    'smallmoney': st.number_input,
    'money': st.number_input,
    'datetime2': st.date_input,
    'smalldatetime': st.date_input,
    'datetimeoffset': st.date_input,
    'nchar': st.text_input,
    'nvarchar': st.text_input,
    'ntext': st.text_area,
    'image': st.file_uploader,
    'cursor': st.text_input,
    'sql_variant': st.text_input,
    'table': st.text_input,
    'uniqueidentifier': st.text_input,
    'spatial': st.file_uploader,
    'bool': st.checkbox,
    'fixed': st.text_input,
    'national': st.text_input,
    'character': st.text_input,
    'txid_snapshot': st.text_input,
    'uuid': st.text_input,
    'xml': st.file_uploader,
    'pg_lsn': st.text_input,
    'pg_ndistinct': st.number_input,
    'pg_node_tree': st.text_area,
    'tsvector': st.text_area,
    'json': st.text_area,
    'jsonb': st.text_area,
    'int4range': st.number_input,
    'int8range': st.number_input,
    'numrange': st.number_input,
    'tsrange': st.text_input,
    'tstzrange': st.text_input,
    'daterange': st.date_input,
    'pg_lsn': st.text_input,
    'uuid': st.text_input,
    'xml': st.file_uploader,
    'json': st.text_area,
    'jsonb': st.text_area,
    'int4range': st.number_input,
    'int8range': st.number_input,
    'numrange': st.number_input,
    'tsrange': st.text_input,
    'tstzrange': st.text_input,
    'daterange': st.date_input,
    'pg_lsn': st.text_input
}

default_values ={
      "varchar":"",
      "int":0,
      "date":datetime.date.today(),
      "datetime":datetime.datetime.now(),
      "timestamp":time.time(),
      "text":"",
      "blob":"",
      "enum":"",
      "set":"",
      "bit":0,
      "bool":False,
      "tinyint":0,
      "smallint":0,
      "mediumint":0,
      "bigint":0,
      "decimal":0,
      "integer":0,
      "double":0,
      "float":0,
      "char":"",
      "tinytext":"",
      "mediumtext":"",
      "longtext":"",
      "year":0
   }
